### ISSUE TITLE
vending machines refresh rate ??

### ISSUE THREAD

**Issue by C74K** [liamcottle/atlas-for-rust#7]
how to incrase vending machines refresh rate ??

**Comment by liamcottle** [comment]
This is hardcoded to 15 seconds to avoid getting rate limited.

https://github.com/liamcottle/atlas-for-rust/blob/master/src/components/RustPlus.vue#L526

If you click the refresh button (next to the "Search Vending Machines" button), it will refresh all of the map markers which includes the vending machines contents.
